add new commands add-server and delete-server add polling support for synchronous behavior

diff --git a/commands/delete-server/script b/commands/delete-server/script
--- a/commands/delete-server/script
+++ b/commands/delete-server/script
@@ -9,15 +9,15 @@
 # The `command` and `usage` comments describe the command
 # and show its options.
 # 
-#/ command: gogrid:get-avail-ip: "Get an available IP Address thru the REST API"
-#/ usage: rerun gogrid:get-avail-ip  --apikey <>  --secret <> [ --ip-type <Public>] 
+#/ command: gogrid:delete-server: "Delete a GoGrid server"
+#/ usage: rerun gogrid:delete-server  --server-name <>  --apikey <>  --secret <> 
 
 # Load common functions
 # ---------------------
 
 # Load the function library for this module.
 # This loads rerun functions, too.
-. $RERUN_MODULE_DIR/lib/functions.sh get-avail-ip || { 
+. $RERUN_MODULE_DIR/lib/functions.sh delete-server || { 
   echo >&2 "Failed loading function library." ; exit 1 ; 
 }
 
@@ -29,7 +29,7 @@
 # Trap errors and exit. The call to `rerun_die` will print the
 # the error message and exit with the error command exit status. 
 
-trap 'rerun_die $? "*** command failed: gogrid:get-avail-ip. ***"' ERR
+trap 'rerun_die $? "*** command failed: gogrid:delete-server. ***"' ERR
 
 # Run [set] `nounset` to treat unset variables as errors. Set [pipefail]
 # so a pipeline return status is the value of the last 
@@ -47,7 +47,7 @@ set -o nounset -o pipefail
 # declared by `rerun` or by the option parser function.
 
 #/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
-#/ option-variables: APIKEY SECRET IP_TYPE
+#/ option-variables: SERVER_NAME APIKEY SECRET
 
 # The `rerun_options_parse` function processes the command line
 # arguments. Each accepted command line flag results in setting 
@@ -59,30 +59,47 @@ rerun_options_parse "$@"
 # Command implementation
 # ----------------------
 
-case ${IP_TYPE} in
-   "Public")
-      ;;
-   "Private")
-      ;;
-   *)
-       rerun_die "Invalid type: ${IP_TYPE}"
-      ;;
-esac
+METHOD="/grid/server/delete?name=${SERVER_NAME}"
 
-METHOD="/grid/ip/list?ip.type=${IP_TYPE}"
+rerun gogrid:api --apikey "${APIKEY}" --secret "${SECRET}" --method "${METHOD}"
 
-#
-# jq executable
-#
-JQ="$(which jq)"
-
-if  [ -z "${JQ}" ]
-then
-   rerun_die "Unable to find the jq command"
-fi
-
-rerun gogrid:api --apikey "${APIKEY}" --secret "${SECRET}" --method "${METHOD}" | \
-   jq  -r '[ .list[] | .state.name as $state | if $state == "Unassigned" then  .  else empty end ][0]|.ip'
+#rerun gogrid:get-server --apikey KEY --secret SECRET --server-name mycentos62-64  | jq -r '.list[].state.name'
+#could be On, Off, but then will result in error when it does not exist
+#state:On
+#state:On
+#state:On
+#state:Off
+#state:Off
+#state:Off
+#state:Off
+#state:Off
+#state:Off
+#state:Off
+#state:Off
+#state:Off
+#state:Off
+#state:Off
+#state:Off
+#state:Off
+#state:Off
+#state:Off
+#state:Off
+#state:Off
+#state:Off
+#state:Off
+#state:Off
+#state:Off
+#state:Off
+#state:Off
+#state:Off
+#state:Off
+#state:Off
+#state:Off
+#state:Off
+#state:Off
+#state:Off
+#state:ERROR: ERROR getURL https://api.gogrid.com/api/grid/server/get?name=mycentos62-64&sig=488b6c379409ce1b8be68b6d9c8fcfe1&format=json&v=1.9&api_key=9a08f45afc8dc59e
+#ERROR: *** command failed: gogrid:get-server. ***
 
 # Done. Exit with last command exit status.
 exit $?
